version: '3.6'

networks:
  rabbitmq-alegra:
    driver: bridge

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    networks:
      - rabbitmq-alegra
    ports:
      - "8090:15672"
    volumes:
      - ./rabbit-init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Custom RabbitMQ configuration
      - ./rabbit-init/definitions.json:/etc/rabbitmq/definitions.json # Custom RabbitMQ definitions
  gateway:
    build: ./gateway
    ports:
      - "8080:80"
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"
      INVENTORY_SERVICE: "inventory"
      KITCHEN_SERVICE: "kitchen"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - rabbitmq-alegra
    depends_on:
      gateway:
        condition: service_started
      inventory:
        condition: service_started
      kitchen:
        condition: service_started
    environment:
      VITE_BACKEND_URL: "gateway"
      VITE_BACKEND_PORT: "8080"
  inventory:
    build: ./inventory-management
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"
  kitchen:
    build: ./kitchen
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"