networks:
  rabbitmq-alegra:
    driver: bridge

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    networks:
      - rabbitmq-alegra
    ports:
      - "8090:15672"
    volumes:
      - ./rabbit-init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Custom RabbitMQ configuration
      - ./rabbit-init/definitions.json:/etc/rabbitmq/definitions.json # Custom RabbitMQ definitions
  database:
    image: 'mysql'
    networks:
      - rabbitmq-alegra
    environment:
      MYSQL_DATABASE: 'alegra-test'
      MYSQL_ROOT_PASSWORD: 'Alegra1Test*Pass1'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
      database:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"
      INVENTORY_SERVICE: "inventory"
      KITCHEN_SERVICE: "kitchen"
      DB_HOST: "database"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - rabbitmq-alegra
    depends_on:
      gateway:
        condition: service_started
      inventory:
        condition: service_started
      kitchen:
        condition: service_started
      database:
        condition: service_started
  inventory:
    build: ./inventory-management
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
      database:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"
      DB_HOST: "database"
  kitchen:
    build: ./kitchen
    networks:
      - rabbitmq-alegra
    depends_on:
      rabbitmq:
        condition: service_started
      database:
        condition: service_started
    environment:
      RABBITMQ_HOST: "rabbitmq"
      DB_HOST: "database"